# Zadanie
1.  Zbudowac model fraudu, taki, że
1.  Skuteczność modelu była wysoka (model był w stanie poprawnie wyłapać jak najwięcej fraudów)
1.  Straty finansowe były niskie (kwota transakcji fraudowych niewyłapanych przez model/kwota wszystkich transakcja liczona zbiorze testowym)

Dane: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

## 1.  Zbudować pierwszy model

In [3]:
!kaggle datasets download mlg-ulb/creditcardfraud

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/cli.py", line 68, in main
    out = args.func(**command_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/api/kaggle_api_extended.py", line 1741, in dataset_download_cli
    with self.build_kaggle_client() as kaggle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/kaggle/api/kaggle_api_extended.py", line 688, in build_kaggle_client
    username=self.config_values['username'],
             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'username'

In [2]:
!unzip creditcardfraud.zip

unzip:  cannot find or open creditcardfraud.zip, creditcardfraud.zip.zip or creditcardfraud.zip.ZIP.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('creditcard.csv')

In [ ]:
df_sample = df.sample(50000, random_state=1)  #  próbka danych

In [ ]:
df_sample.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
169876,119907.0,-0.611712,-0.769705,-0.149759,-0.224877,2.028577,-2.019887,0.292491,-0.523020,0.358468,...,-0.075208,0.045536,0.380739,0.023440,-2.220686,-0.201146,0.066501,0.221180,1.79,0
127467,78340.0,-0.814682,1.319219,1.329415,0.027273,-0.284871,-0.653985,0.321552,0.435975,-0.704298,...,-0.128619,-0.368565,0.090660,0.401147,-0.261034,0.080621,0.162427,0.059456,1.98,0
137900,82382.0,-0.318193,1.118618,0.969864,-0.127052,0.569563,-0.532484,0.706252,-0.064966,-0.463271,...,-0.305402,-0.774704,-0.123884,-0.495687,-0.018148,0.121679,0.249050,0.092516,0.89,0
21513,31717.0,-1.328271,1.018378,1.775426,-1.574193,-0.117696,-0.457733,0.681867,-0.031641,0.383872,...,-0.220815,-0.419013,-0.239197,0.009967,0.232829,0.814177,0.098797,-0.004273,15.98,0
134700,80923.0,1.276712,0.617120,-0.578014,0.879173,0.061706,-1.472002,0.373692,-0.287204,-0.084482,...,-0.160161,-0.430404,-0.076738,0.258708,0.552170,0.370701,-0.034255,0.041709,0.76,0

In [ ]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
from sklearn.model_selection import train_test_split
X = df_sample.drop(columns =['Class'], axis=1)  #  ja nie korzystam ze zmiennej time
y = df_sample['Class']

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X, y = df.drop(columns =['Class'], axis=1), df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf_tree = DecisionTreeClassifier(random_state=42)
clf_tree.fit(X_train_scaled, y_train)
clf_tree.score(X_test_scaled, y_test)

0.9991381786842861

In [ ]:
y_test

43428     1
49906     0
29474     0
276481    0
278846    0
         ..
211399    0
245040    0
97433     0
94007     0
176304    0
Name: Class, Length: 93987, dtype: int64

In [ ]:
X_test.shape

(93987, 30)

In [ ]:
df_validation()

NameError: name 'df_validation' is not defined

In [ ]:
df_validation = pd.DataFrame()
df_validation["Amount"] = X_test['Amount']
df_validation["Class"] = y_test
df_validation["predicted"] = clf_tree.predict(X_test_scaled)


df_loses = df_validation[df_validation['Class'] == 1]
total_loss = df_loses['Amount'].sum()

mask = (df_loses['predicted'] == 0) & (df_loses['Class'] == 1)
model_loss = df_loses[mask]['Amount'].sum()
model_loss/total_loss

0.2508290678658435

In [ ]:
df_validation = pd.DataFrame()
df_validation["Amount"] = X_train['Amount']
df_validation["Class"] = y_train
df_validation["predicted"] = clf_tree.predict(X_train_scaled)


df_loses = df_validation[df_validation['Class'] == 1]
total_loss = df_loses['Amount'].sum()

mask = (df_loses['predicted'] == 0) & (df_loses['Class'] == 1)
model_loss = df_loses[mask]['Amount'].sum()
model_loss/total_loss

0.0

In [ ]:
df_test = pd.DataFrame()
df_test['Class'] = y_test
df_test['Amount'] = X_test['Amount']
df_test['Predicted'] = clf_tree.predict(X_test)
df_test.head()

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(

        Class  Amount  Predicted
43428       1  364.19          1
49906       0  520.12          0
29474       0   31.00          0
276481      0    1.50          0
278846      0    0.89          0

In [ ]:
df_validation

        Amount  Class  predicted
134955    2.97      0          0
84470    72.73      0          0
176085  387.80      0          0
79348   105.54      0          0
63554    28.45      0          0
...        ...    ...        ...
119879    1.98      0          0
259178   89.23      0          0
131932    3.94      0          0
146867    1.00      0          0
121958  113.00      0          0

[190820 rows x 3 columns]

In [ ]:
df_test_loses = df_test[df_test['Class'] == 1]
total_loss = df_test_loses['Amount'].sum()
total_loss

mask = (df_test_loses['Predicted'] == 0) & (df_test_loses['Class'] == 1)

model_loss = df_test_loses[mask]['Amount'].sum()
model_loss
model_loss/total_loss*100

34.720652466008836

In [ ]:
df_validation = pd.DataFrame()
df_validation["Amount"] = X_test['Amount']
df_validation["Class"] = y_test
df_validation["predicted"] = clf_tree.predict(X_test_scaled)


df_loses = df_validation[df_validation['Class'] == 1]
total_loss = df_loses['Amount'].sum()

mask = (df_loses['predicted'] == 0) & (df_loses['Class'] == 1)
model_loss = df_loses[mask]['Amount'].sum()
model_loss/total_loss

0.2508290678658435

In [ ]:
from sklearn import linear_model
from sklearn import tree
from sklearn import neighbors

In [ ]:
clf = linear_model.LogisticRegression()

In [ ]:
def model_validation(model, X_train_scaled, X_test_scaled, y_train, y_test):

  clf = model
  clf.fit(X_train_scaled, y_train)

  df_validation = pd.DataFrame()
  df_validation["Amount"] = X_test['Amount']
  df_validation["Class"] = y_test
  df_validation["predicted"] = clf.predict(X_test_scaled)

  df_loses = df_validation[df_validation['Class'] == 1]
  total_loss = df_loses['Amount'].sum()

  mask = (df_loses['predicted'] == 0) & (df_loses['Class'] == 1)
  model_loss = df_loses[mask]['Amount'].sum()

  return model_loss/total_loss, clf.score(X_test_scaled, y_test)

In [ ]:
model_validation(neighbors.KNeighborsClassifier(n_neighbors=3), X_train_scaled, X_test_scaled, y_train, y_test)

(0.24546331616377637, 0.9995424899188186)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
classifiers = {
    "LogisiticRegression": LogisticRegression(random_state=42),
    "KNearest": KNeighborsClassifier(),
    "Support Vector Classifier": SVC(random_state=42),
    "DecisionTreeClassifier": DecisionTreeClassifier(random_state=42),
    "RandomForestClassifier": RandomForestClassifier(class_weight='balanced', random_state=42)
}

In [ ]:
X, y = df.drop(columns =['Class'], axis=1), df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
for key, classifier in classifiers.items():
  print(key + ":")
  print(model_validation(classifier, X_train_scaled, X_test_scaled, y_train, y_test))

LogisiticRegression:
(0.45698612354542945, 0.9992552161469139)
KNearest:
(0.25234990261664836, 0.9994467319948503)
Support Vector Classifier:
(0.5744912888523842, 0.9993616138402119)
DecisionTreeClassifier:
(0.2508290678658435, 0.9991381786842861)
RandomForestClassifier:
(0.29099878264691814, 0.9996063285347974)

## Zadanie: stworzyć najlepszy model korzystająć z grid-search i utworzyć projekt w pycharm (load_data, train, predict)

In [ ]:
# najlepszy model korzystająć z grid-search

from sklearn.model_selection import GridSearchCV

# Define the parameter grid for RandomForestClassifier
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Create a RandomForestClassifier instance
rf_classifier = RandomForestClassifier(random_state=42, class_weight='balanced')

# Perform GridSearchCV
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='f1', n_jobs=-1) # Use f1 scoring for imbalanced datasets
grid_search.fit(X_train_scaled, y_train)

# Get the best model and its score
best_rf_classifier = grid_search.best_estimator_
best_score = grid_search.best_score_

print(f"Best RandomForestClassifier parameters: {grid_search.best_params_}")
print(f"Best f1 score: {best_score}")


# Evaluate the best model
loss, accuracy = model_validation(best_rf_classifier, X_train_scaled, X_test_scaled, y_train, y_test)
print(f"Loss ratio for best model: {loss}")
print(f"Accuracy for best model: {accuracy}")